# =====================================================================================
# Proyecto: jail-bash
# Componente: config/jail.conf
# Descripción: Variables de entorno globales y lista blanca de seguridad
# Autor: kdefsys
# =====================================================================================

# Ruta absoluta del directorio del sistema host que se transformará en la raíz (/) aislada
# RECOMENDACIÓN: Usa una ruta bajo /var/lib o /tmp para pruebas seguras
JAIL_PATH="/var/lib/jailbash/sandbox"

# LISTA BLANCA DE COMANDOS (Binarios del sistema autorizados)
# Nuestro motor dinámico resolverá automáticamente las librerías dinámicas (.so) para cada uni
COMMANDS_WHITELIST=(
	"/bin/bash"
	"/bin/ls"
	"/bin/cat"
	"/bin/mkdir"
	"/bin/rm"
	"/usr/bin/id"
	"/usr/bin/whoami"
)
